project:
  type: website
  output-dir: docs

website:
  title: "IASE 2024 Roundtable Conference"
  favicon: images/iase-icon.png
  search: false
  body-footer: "<div class='footsy'>For questions or comments, contact <a href='mailto:iase2024.roundtable@gmail.com'>iase2024.roundtable@gmail.com</a></div>"
  navbar:
    title: false
    pinned: false
    background: success
    left:
      - text: "Home"
        file: index.qmd
      - themes.qmd
      - program.qmd
      - text: About
        file: about.qmd
      - text: "Local info"
        file: local.qmd
      - registration.qmd
      - notices.qmd
      
format:
  html:
    page-layout: full
    title-block-banner: false
    include-in-header: extra_code.html
    include-before-body: header.html
    theme: flatly.scss
    css: styles.css
    mainfont: Tahoma
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 0px
      gutter-width: 1.5rem


