---
title: "Local information"
---

## Venue

*To be updated*

## Visas

To find out if you need a visa to enter New Zealand and for information on the visa application process, please consult the [New Zealand government website](https://www.govt.nz/browse/immigration-and-visas/visitor-visas-and-the-nzeta/). Most people visiting NZ must pay the NZD$35 International Visitor Levy. If you require a Visa, you can request an invitation letter for your Visa application by emailing [iase2024.roundtable@gmail.com](mailto:iase2024.roundtable@gmail.com) after registering for the conference. Note that organisers cannot influence or accept responsibility for the processing of Visa applications. Delegates are advised to apply for visas well in advance of the conference, and before booking non-refundable flight tickets and accommodation.

## Travel

[Auckland International Airport](https://www.aucklandairport.co.nz/) is the main hub for travel in New Zealand, for both international and domestic flights. Unfortunately, there are currently no public transport options for getting from the airport to the conference venue or the Auckland CBD. Depending on your time of arrival, there should be plenty of  [taxis](https://www.aucklandairport.co.nz/transport/taxis-and-shuttles) available. You can also book [Super Shuttle](www.supershuttle.co.nz) for a direct ride from the airport to your accommodation, or use various [rideshare options](https://www.aucklandairport.co.nz/transport/rideshare) such as Uber.

## Accommodation

*To be updated*

## Meals

Lunch and refreshments will be provided to attendees on all four days of the conference (2-5 July) at the conference venue (included in registration fees). 

For other meals, there are diverse options available in the many restaurants nearby in Parnell. Alternatively the suburb of Newmarket and the Auckland CBD and waterfront have an even wider array of food options, both within 30 mins walk or a short Uber ride.