---
title: "Theme & papers"
---

## Conference theme

The overall theme of the conference is *Connecting data and people for inclusive statistics and data science education***.** Given that the creation and use of data is a human-driven process, this conference aims to discuss the inclusivity of the teaching and learning experiences for both students and teachers within statistics and data science. Through a mixture of formats including extensive discussions in small groups, the meeting will advance current knowledge about conceptual frameworks, teaching methods, technology solutions, and curricular materials. Within the overall theme we will focus on the following topics:

### Topic 1: Supporting learners with diverse needs and abilities

This topic will consider questions such as: How do we design statistical learning environments to support learners with diverse social, cognitive, and/or physical abilities? How do we transfer ideas from and take on new perspectives to statistics and data science education drawing from disability studies and inclusive education? How do we create digital tools that afford access to learners that see and interact with the world in diverse ways?

### Topic 2: Creative approaches to supporting learners in under-resourced contexts

This topic will consider questions such as: How can statistics and data science concepts be taught in settings where there is limited access to digital technologies? How is statistics and data science education carried out or continued in conflict zones? How can multivariate data be visualised, analysed, and communicated without using digital tools? What are ways learners can visualise data in their community drawing from the assets of their community? What does statistics and data science education look like in remote and rural settings?

### Topic 3: Drawing from multiple ways of knowing in the teaching and learning of statistics and data science

This topic will consider questions such as: How do indigenous ways of knowing data and the world inform new ways of envisioning the teaching and learning of data? How are ethno-statistics developed in different settings? How is technology designed or used to leverage different ways of knowing in the exploration of data? How are asset and community based approaches used in the teaching and learning of data? How is data collected and used in different communities, cultures, and social groups?

### Topic 4: Considerations of socio-political aspects of statistics and data science education

This topic will consider questions such as: How do we support learners in interrogating issues of bias and misuse of data to consider ethical uses of data? What data ethical principles are important for learners? How do we consider ethical issues in terms of who owns data and who can use it particularly when that data is from and about historically marginalised groups? How do we support learners in understanding issues of data privacy? How do we increase access to technological tools for connecting people and data? How can we rethink the underlying logic of statistics challenging its roots in eugenic perspectives? How do we use data to connect people in fair and just ways?

### Topic 5: Interdisciplinary approaches to engaging in data and data literacy

This topic will consider questions such as: How do frameworks, theories, and epistemologies from other disciplines provide different perspectives and approaches to the teaching and learning of statistics? How do interdisciplinary efforts teach us more about the teaching and learning of statistics and data science? How do other disciplines approach the teaching and learning of data and data literacies? What is the role of data and statistics education in STEM and STEAM efforts? How do digital tools support interdisciplinary work and perspectives for investigating data? What are the educational challenges in teaching statistics from an interdisciplinary perspective?

### Topic 6: Taking a humanistic stance in teaching and learning with and about data

This topic will consider questions such as: How do we design learning experiences for learners that involve personally relevant data? How do we use technology in ways to connect people and data? How do we draw from and lift up learners of diverse identities in teaching and learning data literacies? How do we design meaningful learning environments taking sociopolitical issues into account? How do we centre the learner in experiences with using and learning about data?

## Key dates

<mark>Note that the due dates for paper and workshop submissions have been extended from the dates provided in the [initial call for submissions](refs/IASE_2024_roundtable_conference_call_for_submissions.pdf).</mark>

-   **5 January 2024** - Paper/workshop/poster/discussant submissions due

---

-   **9 February 2024** - Notification of paper/workshop/poster/discussant acceptance

---

-   **15 March 2024** - First draft of workshop plan or full six-page paper due

-   **24 May 2024** - Paper authors receive peer-review feedback

---

-   **21 June 2024** - Paper for conference due

-   **31 October 2024** - Final paper for publication due

## Papers, workshops, and posters

The IASE 2024 Roundtable is now accepting applications for contributions in the form of papers, workshops, posters and discussant leaders that fit the theme **Connecting data and people for inclusive statistics and data science education** and that address one of six topics described above. 

* For a **paper**, the submission will require a detailed description of the planned paper (ca. 300 words) including the following sections: Purpose, Design/Methodology, Results/Outcomes, Implications for theory and practice, and Contribution to the theme of the Roundtable and its topics.
* For a **workshop**, the submission will require a detailed description of the workshop (ca. 300 words) including the following sections: Purpose, Learning objectives, Key learning activities, Implications for theory and practice, and Contribution to the theme of the Roundtable and its topics.
* For a **poster**, the submission will require a detailed description of the planned poster (ca. 300 words) including the following sections: Purpose, Design/ Methodology, Results/Outcomes, Implications for theory and practice, and Contribution to the theme of the Roundtable and its topics.
* For a **discussant leader**, the submission will require an extended description of relevant background and interest (200-300 words). 

Please [use this Google form](https://forms.gle/Mt7uXxpkrvALT2QV7) to make your submission.
